#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# Here are some helpfull stuff
# https://gitlab.com/GitMaster210/my-config-files/-/blob/master/SpaceVim/init.toml
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # Custom config
    bootstrap_before = "myconfig#before"
    bootstrap_after = "myconfig#after"

[[layers]]
    name = "fzf"
    
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30


#=============================================================================
# My Custom Plugins
#=============================================================================

[[custom_plugins]]
  repo = "https://github.com/junegunn/fzf.vim"
  merged = 0
[[custom_plugins]]
  repo = "https://github.com/junegunn/fzf"
  merged = 0
